experiments:
- name: isomerization_model_inj2
  model: examples/isomerization/isomerization_model.cps
  data: examples/isomerization/data_W392Y_inj2.csv
  experiment_info:
    cell_compartment_name: cell
    syringe_compartment_name: syringe
    cell_volume: 0.0002071
    cell_species_initial_conc:
      M14_3_3: 147.5
    syringe_species_initial_conc:
      PRLR_trans{syringe}: 1397.0
  parameters:
    N_M14_3_3_isomerization_model_inj2: 0.74
    Kd_cis: 0.338
    k_off_cis: 
      value: 1.0
      fit: False
    k_off_trans: 
      value: 1.0
      fit: False
    k_cis_trans: 
      value: 0.02
      fit: False
    K_cis_trans: 
      value: 0.386962552
      fit: False
    R_Kd_trans_cis: 
      value: 20.0
      fit: False
    dH_cis_binding: -20000
    dH_trans_binding: -10000.0
    dH_iso_cell:
      value: 0
      fit: False
    Offset_isomerization_model_inj2: 0
